baseurl = "https://www.karansinghal.com"
title = "Karan Singhal"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"
publishDir = "docs"

paginate = 20
canonifyurls = true

pygmentsstyle = "friendly"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = ""

[params]
    author = "Karan Singhal"
    info = """I lead the Health AI team at OpenAI, working on LLMs for health and AI safety."""
    infosmall = """Our work aims to:
* **Universalize access to medical expertise**: make health intelligence accessible to everyone
* **Use health as a testbed for safety**: incentivize alignment research by developing LLMs in a high-stakes setting
* **Develop better plans for high-stakes AI deployment**: learn how to iteratively deploy better, given benefits and risks

Our team at OpenAI is hiring [Research Scientists / Engineers](https://openai.com/careers/research-scientist-health-ai/)! Please apply if you have experience with practical LLM safety/alignment–no health expertise required.

My previous work at Google includes [Med-PaLM](https://www.nature.com/articles/s41586-023-06291-2) and [Med-PaLM 2](https://arxiv.org/pdf/2305.09617.pdf), launched in Google Cloud and featured in Nature, Scientific American, The Economist, BBC, and other outlets."""
    description = "Karan Singhal leads Health AI at OpenAI, working on LLMs for health and AI safety."
    keywords = "karan,singhal,openai,health ai,ai safety,medical AI,med-palm,federated,medpalm,federated learning,representation learning,stanford,google,medlm"
    avatarurl = "images/karan_compressed.png"
    avatarurl_webp = "images/karan.webp"

    favicon_32 = "/images/favicon-32x32.png"
    favicon_16 = "/images/favicon-16x16.png"

    footercontent = ""

    hidecredits = true
    hidecopyright = true
    hidefootercontent = true

    rtl = false

    math = true
    custom_css = []

# Social links
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 2
    url = "https://twitter.com/thekaransinghal/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin fa-2x"
    weight = 4
    url = "https://www.linkedin.com/in/karan1149/"
[[params.social]]
    name = "Google Scholar"
    icon = "fab fa-solid fa-google-scholar fa-2x"
    weight = 3
    url = "https://scholar.google.com/citations?user=nMfflL0AAAAJ&hl=en"

#[[menu.main]]
#    name = "Notes"
#    weight = 1
#    url  = "/notes/"
