baseurl = "https://www.karansinghal.com"
title = "Karan Singhal"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"
publishDir = "docs"

paginate = 20
canonifyurls = true

pygmentsstyle = "friendly"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = ""

[params]
    author = "Karan Singhal"
    info = ""
    description = "John Doe's personal website"
    keywords = "karan,singhal,"
    avatarurl = "images/karan.png"

    favicon_32 = "/images/favicon-32x32.png"
    favicon_16 = "/images/favicon-16x16.png"

    footercontent = ""

    hidecredits = true
    hidecopyright = true
    hidefootercontent = true

    rtl = false

    math = true
    custom_css = []

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/karan1149/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 2
    url = "https://twitter.com/karan1149/"
[[params.social]]
    name = "Pocket"
    icon = "fab fa-get-pocket fa-2x"
    weight = 4
    url = "https://getpocket.com/@karan1149/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin fa-2x"
    weight = 4
    url = "https://www.linkedin.com/in/karan1149/"

# Menu links
[[menu.main]]
    name = "Posts"
    weight = 1
    url  = "/posts/"